title: Grocery Images Classifier
description: Classify grocery images using deep learning
about:
  This is a Grocery Images Classifier (currently only cucumbers and pickles) using Deep Learning built on top of Pytorch.


  The project was built by [Kris Johnson](https://github.com/krisrjohnson/fastai/tree/master/food_classifier) 
  Heavily used for web deployment:\
  Pattaniyil, Nidhin and Shaikh, Reshama, [Deploying Deep Learning Models On Web And Mobile](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/), 2019
  Developing the models leverages [fastai](https://www.fast.ai)'s Practical Deep Learning for Coders class.


code: https://github.com/krisrjohnson/fastai/tree/master/food_classifier

sampleImages:
  - name: pickle
    url: https://upload.wikimedia.org/wikipedia/commons/b/bb/Pickle.jpg
  - name: cucumber
    url: https://upload.wikimedia.org/wikipedia/commons/a/a3/Cucumber_BNC.jpg
  - name: eggplant (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: table (not in training & not a food)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 